apiVersion: v1
kind: Template
metadata:
  name: jenkins-dreamer
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jenkins-dreamer
    labels:
      service: jenkins-dreamer
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      deploymentconfig: jenkins-dreamer
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: jenkins-dreamer
          service: jenkins-dreamer
      spec:
        containers:
          - name: jenkins-dreamer
            image: ${IMAGE}:${IMAGE_TAG}
            resources: {}
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: false
            env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: IDLE_AFTER
                value: "1"
              - name: WAIT_TIME
                value: "5"
              - name: NGINX_STATUS_UUID
                value: "e93b3be4-5512-4894-afe0-fea40f28115b"
            livenessProbe:
              exec:
                command: ["/opt/jenkins-dreamer/health_check.sh"]
              initialDelaySeconds: 5
              periodSeconds: 15
              timeoutSeconds: 1
            readinessProbe:
              exec:
                command: ["/opt/jenkins-dreamer/health_check.sh"]
              initialDelaySeconds: 10
              timeoutSeconds: 1
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "500m"
            volumeMounts:
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: jenkins-token-c929p
                readOnly: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 29
        dnsPolicy: ClusterFirst
        securityContext: {}
        volumes:
        - name: jenkins-token-c929p
          secret:
            defaultMode: 420
            secretName: jenkins-token-c929p
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: jenkins-dreamer
    name: jenkins-dreamer
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: jenkins-dreamer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: jenkins-dreamer
    name: jenkins
  spec:
    host: ''
    port:
      targetPort: "8080"
    to:
      kind: Service
      name: jenkins-dreamer
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE
  value: vpavlin/dreamer
- name: IMAGE_TAG
  value: latest